# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Add.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPackageWindow(object):
    def setupUi(self, AddPackageWindow):
        AddPackageWindow.setObjectName("AddPackageWindow")
        AddPackageWindow.resize(627, 355)
        AddPackageWindow.setStyleSheet(rootStyleSHeet)
        self.centralwidget = QtWidgets.QWidget(AddPackageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 631, 151))
        self.frame.setStyleSheet("background-color: rgb(20, 167, 130);\n"
"border-bottom-left-radius: 30px;\n"
"border-bottom-right-radius: 30px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(180, 30, 291, 81))
        font = QtGui.QFont()
        font.setFamily("monoespace")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.myTeleButton = QtWidgets.QPushButton(self.centralwidget)
        self.myTeleButton.setGeometry(QtCore.QRect(490, 280, 101, 31))
        self.myTeleButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.myTeleButton.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(24, 199, 152);\n"
"    background-color: rgb(49, 54, 59);\n"
"}\n"
"QPushButton:pressed {\n"
"    color: rgb(13, 109, 83);\n"
"    background-color: rgb(49, 54, 59);\n"
"}")
        self.myTeleButton.setObjectName("myTeleButton")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(250, 270, 151, 51))
        self.downloadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.downloadButton.setObjectName("downloadButton")
        self.packageLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.packageLineEdit.setGeometry(QtCore.QRect(140, 190, 371, 41))
        font = QtGui.QFont()
        font.setFamily("monoespace")
        font.setBold(True)
        font.setWeight(75)
        self.packageLineEdit.setFont(font)
        self.packageLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.packageLineEdit.setObjectName("packageLineEdit")
        AddPackageWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AddPackageWindow)
        self.statusbar.setObjectName("statusbar")
        AddPackageWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddPackageWindow)
        QtCore.QMetaObject.connectSlotsByName(AddPackageWindow)

    def retranslateUi(self, AddPackageWindow):
        _translate = QtCore.QCoreApplication.translate
        AddPackageWindow.setWindowTitle(_translate("AddPackageWindow", "MainWindow"))
        self.label.setText(_translate("AddPackageWindow", "Wheeler"))
        self.myTeleButton.setText(_translate("AddPackageWindow", "By J0x49"))
        self.downloadButton.setText(_translate("AddPackageWindow", "DOWNLOAD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddPackageWindow = QtWidgets.QMainWindow()
    ui = Ui_AddPackageWindow()
    ui.setupUi(AddPackageWindow)
    AddPackageWindow.show()
    sys.exit(app.exec_())
